# Generated by Django 5.2.16 on 2026-07-20 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='inventory',
            new_name='item',
        ),
    ]
